using System.Resources;
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Imazen.Test.Webp")]
[assembly: AssemblyProductAttribute("Imazen.WebP")]
[assembly: AssemblyDescriptionAttribute(".NET wrapper for libwebp")]
[assembly: AssemblyVersionAttribute("9.0.1")]
[assembly: AssemblyFileVersionAttribute("9.0.1")]
[assembly: NeutralResourcesLanguage("zh-Hans")]

namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "9.0.1";
    }
}
